/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat
         * @description 送出一則使用者訊息並取得回答（與 Streamlit 主流程相同之 `answer_with_rag_and_log`）。
         */
        post: operations["post_chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat Stream
         * @description SSE streaming chat endpoint — 與 /chat 相同邏輯但透過 SSE 逐步回傳。
         */
        post: operations["post_chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Services Status */
        get: operations["get_services_status_api_v1_admin_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/services/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Restart Services */
        post: operations["post_restart_services_api_v1_admin_services_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ollama/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ollama Models */
        get: operations["get_ollama_models_api_v1_admin_ollama_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/docker/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Docker Containers */
        get: operations["get_docker_containers_api_v1_admin_docker_containers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ingest Upload */
        post: operations["post_ingest_upload_api_v1_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Preview */
        get: operations["get_source_preview_api_v1_sources_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Config
         * @description 是否啟用 EVAL 寫入（與 eval_log.is_enabled() 一致）。
         */
        get: operations["get_eval_config_api_v1_eval_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Runs
         * @description 線上運行記錄（eval_runs.jsonl），新到舊最多 limit 筆。
         */
        get: operations["get_eval_runs_api_v1_eval_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/batch/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Eval Batch Runs
         * @description 列出 eval/runs 下各批次 run id。
         */
        get: operations["list_eval_batch_runs_api_v1_eval_batch_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/batch/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Batch Detail
         * @description 單一批次：metrics + 逐題 results。
         */
        get: operations["get_eval_batch_detail_api_v1_eval_batch__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stub Info
         * @description 最小可運行範例：後續可改為真實 chat／ingest 端點。
         */
        get: operations["stub_info_api_v1_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_post_ingest_upload_api_v1_ingest_upload_post */
        Body_post_ingest_upload_api_v1_ingest_upload_post: {
            /**
             * Files
             * @description One or more .txt / .md / .pdf / .docx files
             */
            files: string[];
            /**
             * Chat Id
             * @description Conversation id for metadata scoping
             */
            chat_id?: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * ChatRequest
         * @description 對齊 `streamlit_app` 呼叫 `answer_with_rag_and_log` 時所帶參數。
         */
        ChatRequest: {
            /**
             * Message
             * @description 本輪使用者問題（或一鍵審閱預設句）
             */
            message: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /** History */
            history?: components["schemas"]["ChatMessage"][];
            /**
             * Strict
             * @description True 時等同側欄「嚴格只根據知識庫回答」；False 時走完整路由
             * @default false
             */
            strict: boolean;
            /** Chat Id */
            chat_id?: string | null;
            /**
             * Rag Scope Chat Id
             * @description 若設定，檢索僅限該對話上傳之 chunks（對齊「只搜尋此對話上傳的檔案」）
             */
            rag_scope_chat_id?: string | null;
            /** Original Question */
            original_question?: string | null;
            /** Clarification Reply */
            clarification_reply?: string | null;
            /** Chart Confirmation Question */
            chart_confirmation_question?: string | null;
            /** Chart Confirmation Reply */
            chart_confirmation_reply?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: string[];
            /** Chunks */
            chunks: components["schemas"]["ChunkItem"][];
            /** Tool Name */
            tool_name: string;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
            /**
             * Latency Sec
             * @description 本次呼叫耗時（秒），供觀測用
             */
            latency_sec: number;
            /**
             * Next Original Question For Clarification
             * @description 當 tool_name 為 ask_web_vs_rag 時，下一輪請帶入 original_question
             */
            next_original_question_for_clarification?: string | null;
            /**
             * Next Chart Confirmation Question
             * @description 當本輪詢問是否產圖時，下一輪請帶入 chart_confirmation_question
             */
            next_chart_confirmation_question?: string | null;
        };
        /**
         * ChunkItem
         * @description 檢索片段；與 rag 流程 `chunks` 一致，允許額外欄位。
         */
        ChunkItem: {
            /**
             * Tag
             * @default
             */
            tag: string;
            /**
             * Text
             * @default
             */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /** DockerContainerInfo */
        DockerContainerInfo: {
            /** Container Id */
            container_id: string;
            /** Name */
            name: string;
            /** Image */
            image: string;
            /** Status */
            status: string;
            /** State */
            state: string;
        };
        /** DockerContainersResponse */
        DockerContainersResponse: {
            /** Engine Available */
            engine_available: boolean;
            /** Containers */
            containers?: components["schemas"]["DockerContainerInfo"][];
            /** Error */
            error?: string | null;
        };
        /**
         * EvalBatchDetailResponse
         * @description GET /api/v1/eval/batch/{run_id}
         */
        EvalBatchDetailResponse: {
            /** Run Id */
            run_id: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /**
             * Results
             * @description run_*_results.jsonl 每行一筆原始 JSON
             */
            results?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * EvalBatchListResponse
         * @description GET /api/v1/eval/batch/runs
         */
        EvalBatchListResponse: {
            /** Run Ids */
            run_ids?: string[];
            /**
             * Runs Dir
             * @description 解析後之批次結果目錄（供除錯／說明）
             */
            runs_dir: string;
        };
        /**
         * EvalConfigResponse
         * @description GET /api/v1/eval/config
         */
        EvalConfigResponse: {
            /** Eval Log Enabled */
            eval_log_enabled: boolean;
        };
        /**
         * EvalRunEntry
         * @description 單筆線上運行記錄（eval_runs.jsonl 一行）。
         */
        EvalRunEntry: {
            /** Timestamp */
            timestamp?: string | null;
            /**
             * Question
             * @default
             */
            question: string;
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * Tool Name
             * @default
             */
            tool_name: string;
            /**
             * Latency Sec
             * @default 0
             */
            latency_sec: number;
            /**
             * Top K
             * @default 0
             */
            top_k: number;
            /**
             * Source Count
             * @default 0
             */
            source_count: number;
            /** Chat Id */
            chat_id?: string | null;
        };
        /**
         * EvalRunsResponse
         * @description GET /api/v1/eval/runs — 與 eval_log.load_runs(limit) 一致（新到舊）。
         */
        EvalRunsResponse: {
            /** Entries */
            entries?: components["schemas"]["EvalRunEntry"][];
            /**
             * Eval Log Enabled
             * @description 是否啟用寫入 EVAL_LOG（與 eval_log.is_enabled() 一致）；不影響讀取既有檔案。
             */
            eval_log_enabled: boolean;
            /**
             * Limit
             * @description 本次載入筆數上限
             * @default 500
             */
            limit: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @example ok
             * @example degraded
             */
            status: string;
            /**
             * Service
             * @default agent-demo-api
             */
            service: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /** Deps */
            deps?: {
                [key: string]: string;
            };
        };
        /** IngestUploadResponse */
        IngestUploadResponse: {
            /**
             * Mode
             * @default sync
             * @constant
             */
            mode: "sync";
            /**
             * Chunks Ingested
             * @description Number of chunks ingested into Pinecone
             */
            chunks_ingested: number;
            /** Sources Updated */
            sources_updated?: components["schemas"]["SourceEntry"][];
            /** Skipped Files */
            skipped_files?: string[];
        };
        /** OllamaModelInfo */
        OllamaModelInfo: {
            /** Name */
            name: string;
            /** Model Id */
            model_id: string;
            /** Size */
            size: string;
            /** Modified */
            modified: string;
        };
        /** OllamaModelsResponse */
        OllamaModelsResponse: {
            /** Models */
            models?: components["schemas"]["OllamaModelInfo"][];
            /** Error */
            error?: string | null;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Active State
             * @default unknown
             */
            active_state: string;
            /**
             * Sub State
             * @default unknown
             */
            sub_state: string;
            /**
             * Unit File State
             * @default unknown
             */
            unit_file_state: string;
            /** Error */
            error?: string | null;
        };
        /** ServicesRestartRequest */
        ServicesRestartRequest: {
            /**
             * Services
             * @description Service names to restart. Empty means default restart set.
             */
            services?: string[];
        };
        /** ServicesRestartResponse */
        ServicesRestartResponse: {
            /** Requested Services */
            requested_services?: string[];
            /** Restarted Services */
            restarted_services?: string[];
            /** Failed Services */
            failed_services?: string[];
            /** Services */
            services?: components["schemas"]["ServiceStatus"][];
        };
        /** ServicesStatusResponse */
        ServicesStatusResponse: {
            /** Services */
            services?: components["schemas"]["ServiceStatus"][];
        };
        /** SourceEntry */
        SourceEntry: {
            /** Source */
            source: string;
            /** Chunk Count */
            chunk_count: number;
            /** Chat Id */
            chat_id?: string | null;
        };
        /** SourcePreviewResponse */
        SourcePreviewResponse: {
            /** Source */
            source: string;
            /** Chat Id */
            chat_id?: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
        };
        /** SourcesListResponse */
        SourcesListResponse: {
            /** Entries */
            entries?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * StubInfoResponse
         * @description 最小範例端點：確認路由與設定載入。
         */
        StubInfoResponse: {
            /**
             * Message
             * @default stub
             */
            message: string;
            /** Api Version */
            api_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_services_status_api_v1_admin_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesStatusResponse"];
                };
            };
        };
    };
    post_restart_services_api_v1_admin_services_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicesRestartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesRestartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ollama_models_api_v1_admin_ollama_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OllamaModelsResponse"];
                };
            };
        };
    };
    get_docker_containers_api_v1_admin_docker_containers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DockerContainersResponse"];
                };
            };
        };
    };
    post_ingest_upload_api_v1_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_ingest_upload_api_v1_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_v1_sources_get: {
        parameters: {
            query?: {
                chat_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_preview_api_v1_sources_preview_get: {
        parameters: {
            query: {
                /** @description Exact source id, such as uploaded/<chat_id>/<filename> */
                source: string;
                /** @description Optional conversation scope */
                chat_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_config_api_v1_eval_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalConfigResponse"];
                };
            };
        };
    };
    get_eval_runs_api_v1_eval_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_batch_runs_api_v1_eval_batch_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalBatchListResponse"];
                };
            };
        };
    };
    get_eval_batch_detail_api_v1_eval_batch__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalBatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stub_info_api_v1_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StubInfoResponse"];
                };
            };
        };
    };
}
